# Write your MySQL query statement below
    SELECT V.CUSTOMER_ID,COUNT(*) AS count_no_trans
    FROM VISITS AS V
    LEFT JOIN TRANSACTIONS AS T
    ON V.VISIT_ID=T.VISIT_ID
    WHERE T.TRANSACTION_ID IS NULL
    GROUP BY V.CUSTOMER_ID
